- hosts: backends
  remote_user: debian
  become: true
  tasks:
    - name: docker repo add
      shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
        chmod a+r /etc/apt/keyrings/docker.asc
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: install docker
      apt:
        name: [ 'docker' ]
        update_cache: yes
        state: latest

  handlers:
    - name: reload angie
      systemd:
        name: angie
        state: reloaded
