- hosts: initiators
  remote_user: centos
  become: true
  vars:
    disk_dev: /dev/sda
  tasks:
    - name: install multipath
      yum:
        name: [ 'device-mapper-multipath', 'iscsi-initiator-utils' ]
        update_cache: yes
        state: latest
      when: ansible_distribution == 'CentOS'

    - name:  install multipath
      apt:
        name: [ '???' ]
        update_cache: yes
        state: latest
      when: ansible_distribution == 'Debian111'

    - name: copy config
      template:
        src: "{{ item }}"
        dest: "/etc/{{ item }}"
      loop:
        - multipath.conf
      notify:
        - reload multipathd

    - name: start multipathd
      systemd:
        name: multipathd
        state: started

    - name: add disk to multipath
      shell: |
        multipath -W
        multipath -a {{ disk_dev }}
        multipath -r

  handlers:
    - name: restart multipathd
      systemd:
        name: multipathd
        state: restarted

    - name: reload multipathd
      systemd:
        name: multipathd
        state: reloaded
